server:
  port: 8761

eureka:
  instance:
    hostname: server1.com
    # eureka实例名称
    instance-id: server1
  client:
    fetch-registry: true #标识是否检索服务：默认true-检索
    register-with-eureka: true #标识是否向Eureka注册自己：默认true-注册自己
    service-url:
      # defaultZone 默认
#      defaultZone: http://server2.com:8762/eureka,http://server3.com:8763/eureka
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@server2.com:8762/eureka,http://${spring.security.user.name}:${spring.security.user.password}@server3.com:8763/eureka
#      defaultZone: http://peer1:8761${server.servlet.context-path}/eureka
